# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 02:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('pw_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='poke',
            name='poked_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poked', to='users.User'),
        ),
        migrations.AddField(
            model_name='poke',
            name='poker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poker', to='users.User'),
        ),
    ]
